language: node_js
os:
- osx
- linux
node_js: lts/*
install:
- |
  if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  fi
  npm i
script:
- |
  echo ">>> Compile vscode-test"
  yarn && yarn compile
  echo ">>> Compiled vscode-test"
  cd sample
  echo ">>> Run sample integration test"
  yarn && yarn compile && yarn test
cache: yarn
jobs:
  include:
    - stage: test
      script: "npm run test:lint"
    - stage: test
      script: "npm run test"
    - stage: test
      script: "npm run test:security"
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
notifications:
  email:
    recipients: dipustovit@gmail.com
    on_success: change
    on_failure: always